### ISSUE TITLE
It simply won't paint

### ISSUE THREAD

**Issue by LumpySpirit** [jhaakma/joy-of-painting#5]
Set some paper down on a table, then tried to do an ink sketch. The game freezes for a moment as if it were doing something, but nothing happens. From the look of the log, it seems like there are missing textures and screenshots? (Though I don't fully understand how to read logs)
The version of imagemagik I used is the standalone version.
[MWSE.log](https://github.com/jhaakma/joy-of-painting/files/11751822/MWSE.log)

**Comment by jhaakma** [comment]
Was the mod working previously, or is this the first time you've tried it?

**Comment by jhaakma** [comment]
My guess is that because you've installed morrowind into your Documents folder in C:/Users, Windows is preventing JoP from writing the new image files. These permissions errors usually stem from people installing to "Program Files", but it's likely the same problem is happening here. 

If you have a second drive on your computer, create a new Steam install location there (e.g. "E:/games/"), and move your Morrowind install there. If you only have one drive, its a bit trickier because Steam only lets you have one install folder per drive. You can use this tool to safely create a second install folder though: https://github.com/LostDragonist/steam-library-setup-tool/wiki/Usage-Guide. Use that to create a new install location, then move Morrowind there. Again, put it somewhere outside of any special windows locations, like "C:/Games".

**Comment by jhaakma** [comment]
A few options you can try before moving the installation: you can try to set the permissions on your Users or Documents folder, make sure the folder is owned by your user rather than "TrustedUser" or anything else. You can also see whether running MW as admin changes anything, that would at least confirm that this is a permissions issue

**Comment by LumpySpirit** [comment]
Definitely not a permissions issue, I've got Morrowind set to run as admin every time, and all the folders are marked as owned by me.
No other drives, only one drive on my laptop. Unless there's another, less user-hostile way of getting it to work this mod is going to be a hard pass. (especially after installing so much stuff trying to get it to work in the first place!)

**Comment by jhaakma** [comment]
It's either a permissions issue or the "Data Files\textures\jop\saved\Ink Sketch\" directory doesn't exist (which it should because it is packaged with the mod). ImageMagick is failling to write a file to that location, so there's no other explanation I can think of.

**Comment by LumpySpirit** [comment]
Reinstalled the mod and checked the directory, there's no folder for the saved images! Unzipped the mod folder manually, and the folders are all there. Then replaced the missing folders and tried making a sketch again, worked like a charm!
Seems like Vortex is somehow deleting the empty folders without me knowing when it's being installed (Which it shouldn't, since it doesn't normally do that)

**Comment by jhaakma** [comment]
Ah, yeah Vortex doesn't actually support Morrowind modding properly. Morrowind has a lot of quirks that it just doesn't handle very well. I suggest moving to Mod Organiser 2 or Wrye Mash at some point if you want to avoid issues like this in the future.

I'm glad you figured it out though! I'll add a note to the install instructions that Vortex can cause these issues.
